
name: frontend
version: 0.1.0
description: A simple frontend application
type: application
appVersion: "0.10"
apiVersion: v2

dependencies:
- name: backend
  alias: backend
  version: 1.0.0
  repository: 	http://192.168.1.135:8081/repository/helm/
  #version: 1.0.0
  #repository: file://../backend