spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: 'DESKTOP-BON71NE\x01457492'
