spring:
  application:
    name: application
dbMonitor:
  datasets:
  - name: "spaceused"
    enable: true
    type: storedProcedure
    statement: "sp_spaceused"
    parameters:
      objname:
      updateusage: true
      value: true
      mode: ALL
      oneresultset: 1
      include_total_xtp_storage: 0
  - name : "query"
    enable: true
    type: query
    statement: 'select * from dbo.spt_monitor'
