spring:
  application:
    name: application
dbMonitor:
  sp_spaceused:
    type: execute
    statement: sp_spaceused
    parameters:
      - name: objname
      - name: updateusage
        value: true
      - name: mode
        value: ALL
      - name: oneresultset
        value: 1
      - name: include_total_xtp_storage
        value: 0
  query:
    type: query
    statement: "select '123' as abc"
